# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "generic/debian9"

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.

  config.vm.define "host" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "debian"
    subconfig.vm.network "private_network", :libvirt__network_name => "br0"

    subconfig.vm.provision "shell", inline: <<-SHELL
       sudo apt-get update
       sudo apt-get install -y nano htop apt-transport-https ca-certificates curl gnupg2 software-properties-common
       curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
       sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
       sudo apt-get update
       sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    SHELL
end

    config.vm.synced_folder "/config", "/config"
    config.ssh.insert_key = false
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

    config.vm.provider :libvirt do |domain|
        domain.memory = 6024
        domain.cpus = 2
        domain.features = ['acpi', 'apic', 'pae' ]
        domain.graphics_port = 5905
        domain.graphics_ip = '0.0.0.0'
        domain.video_type = 'qxl'
    end

end
