CREATE DATABASE test;
CREATE USER 'test'@'%' IDENTIFIED BY 'test';
GRANT ALL PRIVILEGES ON test.* TO 'test'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE DATABASE print;
CREATE USER 'print'@'%' IDENTIFIED BY 'print';
GRANT ALL PRIVILEGES ON print.* TO 'print'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
