version: '3.1'

services:
  dataflowserver:
    image: dataflowserver:1.4.0
    restart: unless-stopped
    hostname: dataflowserver
    deploy:
      resources:
        limits:
          memory: 2034M
        reservations:
          memory: 2024M
    ports:
      - 9393:9393
      - 9001:9001
      - 9002:9002
      - 9003:9003
    environment:
      TEST: "true"
    external_links:
      - dfskafa:dfskafa
      - dfszookeeper:dfszookeeper
      - dfsmysql:dfsmysql
  dfskafka:
    image: ches/kafka
    restart: unless-stopped
    hostname: dfskafka
    deploy:
      resources:
        limits:
          memory: 522M
        reservations:
          memory: 512M
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: dfskafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 1
      ZOOKEEPER_CONNECTION_STRING: dfszookeeper:2181
    external_links:
      - dfszookeeper:dfszookeeper
  dfszookeeper:
    image: zookeeper
    restart: unless-stopped
    hostname: dfszookeeper
    deploy:
      resources:
        limits:
          memory: 266M
        reservations:
          memory: 256M
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
  dfsmysql:
    image: mysql:5.7
    restart: unless-stopped
    hostname: dfsmysql
    deploy:
      resources:
        limits:
          memory: 266M
        reservations:
          memory: 256M
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: spring
      MYSQL_DATABASE: spring  
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
