version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    restart: unless-stopped
    hostname: elastic
    deploy:
      resources:
        limits:
          memory: 1026M
        reservations:
          memory: 1024M
    ports:
      - 9200:9200
      - 9300:9300
      - 9002:9002
      - 9003:9003
    environment:
      discovery.type: "single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    restart: unless-stopped
    hostname: kibana
    deploy:
      resources:
        limits:
          memory: 1026M
        reservations:
          memory: 1024M
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.3eeper
    restart: unless-stopped
    hostname: zooklogstash
    volumes:
          - /git/docker-repository/ELK-Stack/logstash:/usr/share/logstash/pipeline
    deploy:
      resources:
        limits:
          memory: 266M
        reservations:
          memory: 256M
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch
