entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true

http:
  middlewares:
    basicauthentication:
      basicAuth:
        users:
          - "test:$apr1$X4X4/f1/$XVMCs3g0Ff993DhLsxHqW1" 
          - "test2:$apr1$DIMET5Uu$JJWPKaQ7FVHOBCM8ZmYGh0"
    stripprefix:
      stripPrefix:
        prefixes:
          - "/simple"
          - "/mirror"
  routers:
    simpleservice-router:
      rule: "PathPrefix(`/simple`)"
      service: simpleservice
      middlewares:
      - basicauthentication
      - stripprefix
    mirrorservice-router:
      rule: "PathPrefix(`/mirror`)"
      service: mirrorservice
      middlewares:
      - basicauthentication
      - stripprefix
  services:
    simpleservice:
      loadBalancer:
        servers:
        - url: "http://nuc:8201"
    mirrorservice:
      loadBalancer:
        servers:
        - url: "http://nuc:8003"
