version: '3.1'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/prometheus/etc
      - prometheus_data:/prometheus/data
    command:
      - '--config.file=/prometheus/etc/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/prometheus/console_libraries'
      - '--web.console.templates=/prometheus/consoles'
    ports:
      - 9090:9090
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager/:/alertmanager/etc"
    restart: unless-stopped
    command:
      - '--config.file=/alertmanager/etc/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/grafana
      - ./grafana/provisioning/:/grafana/etc/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: unless-stopped
