# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 2
BOX_IMAGE = "generic/debian9"

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "rangermaster"
    subconfig.vm.network :private_network,
                          ip: "10.0.0.10",
                          :libvirt__netmask => '255.255.255.0',
                          :libvirt__network_name => 'ranger',
                          :libvirt__forward_mode => 'none'

    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nano htop apt-transport-https ca-certificates curl gnupg2 software-properties-common
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher
    SHELL
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "rangernode#{i}"
      subconfig.vm.network :private_network,
                            ip: "10.0.0.#{i + 10}",
                            :libvirt__netmask => '255.255.255.0',
                                  :libvirt__network_name => 'ranger',
                                  :libvirt__forward_mode => 'none'

      subconfig.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y nano htop apt-transport-https ca-certificates curl gnupg2 software-properties-common
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      SHELL
    end
  end

  # Share an additional folder to the guest VM
  config.vm.synced_folder "/config", "/config"

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

  config.vm.provider :libvirt do |domain|
    domain.memory = 6024
    domain.cpus = 1
    domain.features = ['acpi', 'apic', 'pae' ]
  end
end
