version: '3.1'

services:
  crudservice:
    image: wlanboy/crudservice:latest
    hostname: crudservice
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    environment:
      - PORT=8002
      - LOGSTASH=logstash:5044
    ports:
      - 8002:8002
  mirrorservice:
    image: wlanboy/mirrorservice:latest
    hostname: mirrorservice
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    environment:
       - PORT=8844
       - LOGSTASH=logstash:5044
    ports:
      - 8844:8844

networks:
  default:
    external:
      name: spring-net
